name: CI-CD
on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v4.1.1
      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Criação da Imagem docker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            secultceara/editais:v${{ github.run_number }}
            secultceara/editais:latest
            
  CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Pull da imagem do dockerhub
        run: docker pull secultceara/editais:latest
      - name: Restart do docker-compose para atualizar o container com a nova imagem
        run: cd /opt/docker/site-editais/ && docker-compose down && docker-compose up -d
